/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLogo: typeof import('./components/AppLogo.vue')['default']
    AppRate: typeof import('./components/AppRate.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiBtn: typeof import('./../../ui/src/components/btn/UiBtn.vue')['default']
    UiIcon: typeof import('./../../ui/src/components/icon/UiIcon.vue')['default']
    UiInput: typeof import('./../../ui/src/components/input/UiInput.vue')['default']
    UiOverlayMenu: typeof import('./../../ui/src/components/ui-overlay-menu/UiOverlayMenu.vue')['default']
    UiPopup: typeof import('./../../ui/src/components/ui-overlay-menu/UiPopup.vue')['default']
    UiTag: typeof import('./../../ui/src/components/tag/UiTag.vue')['default']
    UiTextField: typeof import('./../../ui/src/components/text-field/UiTextField.vue')['default']
  }
}
