version: '3.9'

services:
  postgres:
    image: postgres:13
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=iforum
    volumes:
      - type: bind
        source: ./.docker/pgdata
        target: /var/lib/postgresql/data
